
const DATE_FORMAT = 'MM/DD/YYYY';
const NUMBER_FORMAT = '0,0.00';
const APP_SECRET_KEY = 'eyJleHAiOjE2MTA4MjkxNzgsImFsZyI6IkhTMjU2IiwiaWF0IjoxNDUzMTQ5MTc4fQ.eyJpZCI6OH0.TUFRtvzL70qgdBVkDWNjjKSzzI6z7wGzkxERzSUuMcc';

exports.DATE_FORMAT = DATE_FORMAT;
exports.NUMBER_FORMAT = NUMBER_FORMAT;
exports.APP_SECRET_KEY = APP_SECRET_KEY;
