
const DATE_FORMAT = 'MM/DD/YYYY';
const NUMBER_FORMAT = '0,0.00';
const APP_SECRET_KEY = 'eyJpYXQiOjE0NTc1NTc0MDYsImV4cCI6MTYxNTIzNzQwNiwiYWxnIjoiSFMyNTYifQ.eyJpZCI6MX0.FIVRju7qroqF1UYFG3d8e_gAUVQbzHWmjjAhgrl4KKw';

const COLOURS = [
  {value: '#b11b1b'},
  {value: '#c52c2c'},
  {value: '#f34336'},
  {value: '#e37272'},
  {value: '#850e4d'},
  {value: '#bd1759'},
  {value: '#e71e62'},
  {value: '#ee6191'},
  {value: '#43127f'},
  {value: '#41117a'},
  {value: '#731d97'},
  {value: '#9b27af'},
  {value: '#ad61bb'},
  {value: '#2d1987'},
  {value: '#4f2ca3'},
  {value: '#673ab6'},
  {value: '#8b6dbf'},
  {value: '#0d47a1'},
  {value: '#176dc1'},
  {value: '#2195f1'},
  {value: '#62b1f1'},
  {value: '#015496'},
  {value: '#0283ca'},
  {value: '#03a7f1'},
  {value: '#4ec1f3'},
  {value: '#005f63'},
  {value: '#0097a7'},
  {value: '#00bad2'},
  {value: '#4bcbdb'},
  {value: '#00493d'},
  {value: '#007567'},
  {value: '#008e81'},
  {value: '#4db5ab'},
  {value: '#194b32'},
  {value: '#388d3c'},
  {value: '#4bad4f'},
  {value: '#73b175'},
  {value: '#2f611b'},
  {value: '#659b37'},
  {value: '#8bc34a'},
  {value: '#aed581'},
  {value: '#7b7116'},
  {value: '#afb42b'},
  {value: '#cbda38'},
  {value: '#dae574'},
  {value: '#f57f17'},
  {value: '#f37e17'},
  {value: '#e7b129'},
  {value: '#ead836'},
  {value: '#fbed75'},
  {value: '#fd6e00'},
  {value: '#f49900'},
  {value: '#fdc007'},
  {value: '#fdd44e'},
  {value: '#d94d00'},
  {value: '#f37b00'},
  {value: '#fd9700'},
  {value: '#f4af49'},
  {value: '#b7330b'},
  {value: '#e04818'},
  {value: '#ea501f'},
  {value: '#fe8a65'},
  {value: '#3e2723'},
  {value: '#5a3e35'},
  {value: '#735145'},
  {value: '#a0877e'},
  {value: '#243035'},
  {value: '#435761'},
  {value: '#607d8b'},
  {value: '#899ba5'},
];

const LOGOS = [
  {value: 'fa-medkit'},
  {value: 'fa-shopping-cart'},
  {value: 'fa-car'},
  {value: 'fa-ambulance'},
  {value: 'fa-subway'},
  {value: 'fa-wheelchair'},
  {value: 'fa-plane'},
  {value: 'fa-taxi'},
  {value: 'fa-bicycle'},
  {value: 'fa-bus'},
  {value: 'fa-motorcycle'},
  {value: 'fa-truck'},
  {value: 'fa-train'},
  {value: 'fa-ship'},
  {value: 'fa-bank'},
  {value: 'fa-beer'},
  {value: 'fa-camera'},
  {value: 'fa-cart-plus'},
  {value: 'fa-child'},
  {value: 'fa-globe'},
  {value: 'fa-heartbeat'},
  {value: 'fa-hdd-o'},
  {value: 'fa-money'},
  {value: 'fa-shield'},
  {value: 'fa-anchor'},
  {value: 'fa-briefcase'},
  {value: 'fa-camera-retro'},
  {value: 'fa-coffee'},
  {value: 'fa-credit-card'},
  {value: 'fa-futbol-o'},
  {value: 'fa-graduation-cap'},
  {value: 'fa-headphones'},
  {value: 'fa-male'},
  {value: 'fa-moon-o'},
  {value: 'fa-music'},
  {value: 'fa-phone'},
  {value: 'fa-plus-circle'},
  {value: 'fa-road'},
  {value: 'fa-tree'},
  {value: 'fa-video-camera'},
  {value: 'fa-archive'},
  {value: 'fa-book'},
  {value: 'fa-binoculars'},
  {value: 'fa-check-square'},
  {value: 'fa-cutlery'},
  {value: 'fa-diamond'},
  {value: 'fa-fire-extinguisher'},
  {value: 'fa-gamepad'},
  {value: 'fa-heart'},
  {value: 'fa-home'},
  {value: 'fa-laptop'},
  {value: 'fa-mortar-board '},
  {value: 'fa-paint-brush'},
  {value: 'fa-pencil'},
  {value: 'fa-phone-square'},
  {value: 'fa-puzzle-piece'},
  {value: 'fa-star'},
  {value: 'fa-trophy'},
  {value: 'fa-umbrella'},
  {value: 'fa-bed'},
  {value: 'fa-birthday-cake'},
  {value: 'fa-building'},
  {value: 'fa-female'},
  {value: 'fa-flag'},
  {value: 'fa-glass'},
  {value: 'fa-trash'},
  {value: 'fa-wifi'},
  {value: 'fa-eur'},
  {value: 'fa-gg-circle'},
  {value: 'fa-krw'},
  {value: 'fa-rub'},
  {value: 'fa-btc'},
  {value: 'fa-ils'},
  {value: 'fa-try'},
  {value: 'fa-gbp'},
  {value: 'fa-inr'},
  {value: 'fa-gg'},
  {value: 'fa-jpy'},
  {value: 'fa-usd'},
  {value: 'fa-stethoscope'},
  {value: 'fa-hospital-o'},
  {value: 'fa-user-md'},
  {value: 'fa-heart-o'},
  {value: 'fa-plus-square'},
];


exports.DATE_FORMAT = DATE_FORMAT;
exports.NUMBER_FORMAT = NUMBER_FORMAT;
exports.APP_SECRET_KEY = APP_SECRET_KEY;
exports.COLOURS = COLOURS;
exports.LOGOS = LOGOS;
