
const DATE_FORMAT = 'MM/DD/YYYY';
const NUMBER_FORMAT = '0,0.00';
const APP_SECRET_KEY = 'eyJpYXQiOjE0NTc1NTc0MDYsImV4cCI6MTYxNTIzNzQwNiwiYWxnIjoiSFMyNTYifQ.eyJpZCI6MX0.FIVRju7qroqF1UYFG3d8e_gAUVQbzHWmjjAhgrl4KKw';

exports.DATE_FORMAT = DATE_FORMAT;
exports.NUMBER_FORMAT = NUMBER_FORMAT;
exports.APP_SECRET_KEY = APP_SECRET_KEY;
